Models/Owner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SAILI.Models
{
    public class Owner
    {
        [Key]
        [StringLength(128)]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public string OwnerID { get; set; }

        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public bool IsDeleted { get; set; }

        [StringLength(128)]
        [DataType(DataType.Text)]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public string UserID { get; set; }

        [ForeignKey("UserID")]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public ApplicationUser user { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        [DataType(DataType.Text)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        [DataType(DataType.Text)]
        [Display(Name = "Middle Name")]
        public string MiddleName{ get; set; } 

        [Required]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        [DataType(DataType.Text)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(128)]
        [Display(Name = "DOB")]
        public string DOB { get; set; }

        [Required]
        [StringLength(10, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 1)]
        [DataType(DataType.Text)]
        [Display(Name = "Address Number")]
        public string AddressNumber { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        [DataType(DataType.Text)]
        [Display(Name = "Address Name")]
        public string AddressName { get; set; }

        [Required]
        [Display(Name = "Postcode")]
        public string PostcodeID { get; set; }

    }
}

Controllers/OwnerController.cs
using SAILI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;
using System.Net;

namespace SAILI.Controllers
{
    [Authorize]
    public class OwnerController : Controller
    {
        private ApplicationDbContext DefaultConnection = new ApplicationDbContext();
        // GET: Owner
        public ActionResult Index()
        {
            return View();
        }

        // GET: Owner/Details/5
        public ActionResult Details(string UserID)
        {
            var owner = DefaultConnection.Users.Find(UserID);
            return View(owner);
        }

        public ActionResult CheckStatusOwner()
        {
            string userId = User.Identity.GetUserId();
            if(User.IsInRole("Administrator"))
            {
                return RedirectToAction("ResourceIndex", "Account");
            }

            SailiRepository repository = new SailiRepository();
            string ownerid = repository.CheckStatus(User.Identity.GetUserId());

            if (!String.IsNullOrEmpty(ownerid))
            {
                return RedirectToAction("CheckStatusTrader", "TraderAccount", new
                {
                    OwnerID = ownerid
                });
            }
            else
            {
                return RedirectToAction("Create", new
                {
                    userId = User.Identity.GetUserId()
                });
            }
        }

        [HttpPost]
        public JsonResult GetPost(string post)
        {
            Postcode postcode = new Postcode();
            List<Postcode> listing = new List<Postcode>();

            string cs = ConfigurationManager.ConnectionStrings["SailiDbContext"].ConnectionString;
            using (SqlConnection con = new System.Data.SqlClient.SqlConnection(cs))
            {
                SqlCommand cmd = new SqlCommand("spGetLocality", con);
                cmd.CommandType = CommandType.StoredProcedure;

                SqlParameter parameter = new SqlParameter();
                parameter.ParameterName = "@postcode";
                parameter.Value = post;

                cmd.Parameters.Add(parameter);
                con.Open();
                SqlDataReader rdr = cmd.ExecuteReader();
                while (rdr.Read())
                {
                    postcode = new Postcode();
                    postcode.PostcodeID = Convert.ToInt32(rdr["postcodeID"]);
                    postcode.postcode = rdr["postcode"].ToString();
                    postcode.Locality = rdr["Locality"].ToString();
                    postcode.State = rdr["State"].ToString();
                    postcode.Country = rdr["Country"].ToString();
                    listing.Add(postcode);
                }

                rdr.Close();
            }

            return Json(listing, JsonRequestBehavior.AllowGet);
        }

        // GET: Owner/Create
        public ActionResult Create(string userId)
        {
            if (userId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if(!userId.Equals(User.Identity.GetUserId()))
            {
                DataSerializer<string>.SecurityPriorityNumberOne(User.Identity.GetUserId());
            }
                
            return View();
        }

        // POST: Owner/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Owner model)
        {
            bool check = false;

            if (model.FirstName == null)
                check = true;
            if (model.MiddleName == null)
                check = true;
            if (model.LastName == null)
                check = true;
            if (model.DOB == null)
                check = true;
            if (model.AddressNumber == null)
                check = true;
            if (model.AddressName == null)
                check = true;
            if (model.PostcodeID == null)
                check = true;
            if (check)
                return View(model);


            char[] delimiter = { ',' };
            string[] temp = model.PostcodeID.Split(delimiter, StringSplitOptions.RemoveEmptyEntries);
            EncryptionServices encryptionService = new EncryptionServices();
            SailiRepository repository = new SailiRepository();
            Vector<Postcode> Locality = new Vector<Postcode>();
            model.UserID = User.Identity.GetUserId();
            model = encryptionService.EncryptOwner(model);

            temp = repository.RemoveEmptyEntries(temp);
            string post = temp[0];
            Locality = repository.GetLocality(post);

            try
            {
                foreach (var item in Locality)
                {
                    if (item == null)
                        break;

                    if(item.postcode.Equals(temp[0].ToString()) && 
                        item.Locality.Equals(temp[1].ToString()))
                    {
                        model.PostcodeID = item.PostcodeID.ToString();
                    }
                }
                DefaultConnection.Owners.Add(new Owner()
                {
                    OwnerID = model.OwnerID,
                    UserID = model.UserID,
                    FirstName = model.FirstName,
                    MiddleName = model.MiddleName,
                    LastName = model.LastName,
                    DOB = model.DOB,
                    AddressNumber = model.AddressNumber,
                    AddressName = model.AddressName,
                    PostcodeID = model.PostcodeID
                });
                 DefaultConnection.SaveChanges();


                return RedirectToAction("CheckStatusTrader", "TraderAccount", new
                {
                    OwnerID = model.OwnerID.ToString()
                });
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Owner/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Owner/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Owner/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Owner/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Owner/Create.cshtml
@model SAILI.Models.Owner

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.0.min.js" type="text/javascript"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
    <link href="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/themes/blitzer/jquery-ui.css" rel="Stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Empty.css")" rel="stylesheet" type="text/css" />
    <meta name="viewport" content="width=device-width" />
    <title>Create Trading Account</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>

    <script type="text/javascript">
        $(document).ready(function () {
            $(function () {
                $("#txtCustomer").autocomplete({
                    source: function (request, response) {
                        var element = $('#txtCustomer').val()
                        if (element.length < 4) {
                            return false;
                        }
                        $.ajax({
                            url: '/Home/GetLocality/',
                            data: JSON.stringify({ 'post': element }),
                            dataType: "json",
                            type: "POST",
                            contentType: "application/json; charset=utf-8",
                            success: function (data) {
                                response($.map(data, function (item) {
                                    return {
                                        label: item.postcode + ', ' + item.Locality + ', ' + item.State,
                                        value: item.value,
                                    };
                                }))
                            },
                            error: function (response) {
                                alert(response.responseText);
                            },
                            failure: function (response) {
                                alert(response.responseText);
                            }
                        });
                    },
                    select: function (e, i) {
                        $("#hfCustomer").val(i.item.val);
                    },
                    minLength: 1
                });
            });
        });
        $(function () {
            $("#DOB").datepicker();
        });
    </script>
    <h2>Create Trader Account</h2>
    <br />
    <section id="Form">
        @using (Html.BeginForm("Create", "Owner", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = Html.Display("First Name") } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control", placeholder = Html.Display("Middle Name") } })
                        @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = Html.Display("Last Name") } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { id = "DOB" } })
                        @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger", placeholder= "MM/DD/YYYY" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.AddressNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AddressNumber, new { htmlAttributes = new { @class = "form-control", placeholder = Html.Display("Address Number") } })
                        @Html.ValidationMessageFor(model => model.AddressNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.AddressName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AddressName, new { htmlAttributes = new { @class = "form-control", placeholder = Html.Display("Address Name") } })
                        @Html.ValidationMessageFor(model => model.AddressName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PostcodeID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PostcodeID, new { htmlAttributes = new { id= "txtCustomer", placeholder = Html.Display("Postcode") } })
                        @Html.ValidationMessageFor(model => model.PostcodeID, "", new { @class = "text-danger" })
                    </div>
                </div>
                    <input type="hidden" id="hfCustomer" name="CustomerId" />
                    <br /><br />

                    <input type="submit" id="btnSubmit" value="Submit" />
                    <br /><br />
                </div>
        }
    </section>
</body>
</html>


Views/Owner/Details.cshtml
@model SAILI.Models.Owner

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Empty.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Owner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostcodeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostcodeID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OwnerID }) |
    @Html.ActionLink("Back to List", "Index")
</p>