Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SAILI.Models
{
    public class Contact
    {
        [Key]
        [DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public int ContactID { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        [DataType(DataType.Text)]
        [Display(Name = "First Name")]
        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        public string FirstName { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        [DataType(DataType.Text)]
        [Display(Name = "Last Name")]
        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        public string LastName { get; set; }

        [Required]
        [StringLength(15, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 8)]
        [DataType(DataType.Text)]
        [Display(Name = "Contact Number")]
        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        public string ContactNumber { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 5)]
        [DataType(DataType.Text)]
        [Display(Name = "Contact Email")]
        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        public string ContactEmail { get; set; }
    }
}

Models/EmailForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SAILI.Models
{
    public class EmailForm
    {
        [Required, Display(Name = "Your name")]
        public string FromName { get; set; }
        [Required, Display(Name = "Your email"), EmailAddress]
        public string FromEmail { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Message { get; set; }
    }
}

Models/Home.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SAILI.Models
{
    public class Home
    {
        [Key]
        [DatabaseGenerated(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity)]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public int HomeID { get; set; }

        [Required]
        [StringLength(5000, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
        [DataType(DataType.Text)]
        [Display(Name = "About")]
        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        public string About { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        [DataType(DataType.Text)]
        [Display(Name = "Help Name")]
        public string HelpName { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 8)]
        [DataType(DataType.Text)]
        [Display(Name = "Help Phone Number")]
        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        public string HelpPhoneNumber { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 5)]
        [DataType(DataType.Text)]
        [Display(Name = "Help Email")]
        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        public string HelpEmail { get; set; }
    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAILI.Models;


namespace SAILI.Controllers
{
    public class ContactController : Controller
    {
        private ApplicationDbContext DefaultConnection = new ApplicationDbContext();
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        // GET: Contact/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Contact/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contact/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contact/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Contact/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contact/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Contact/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/HomeController.cs

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAILI.Models;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;
using SAILI;
using System.Threading.Tasks;
using System.Net.Mail;
using System.Net;
using System.Data.Entity;
using System.IO;
using System.Xml;
using System.Web.Helpers;
using System.Text;

namespace SAILI.Controllers
{

    public class HomeController : Controller
    {

        private ApplicationDbContext DefaultConnection = new ApplicationDbContext();

        public ActionResult Index()
        {
            var model = DefaultConnection.Homes.Find(1);

            return View(model);
        }

        public ActionResult AdminIndex()
        {
            return View(DefaultConnection.Homes.ToList());
        }

        [HttpPost]
        public JsonResult GetLocality(string post)
        {

            Postcode postcode = new Postcode();
            List<Postcode> listing = new List<Postcode>();

            string cs = ConfigurationManager.ConnectionStrings["SailiDbContext"].ConnectionString;
            using (SqlConnection con = new SqlConnection(cs))
            {
                SqlCommand cmd = new SqlCommand("spGetLocality", con);
                cmd.CommandType = CommandType.StoredProcedure;

                SqlParameter parameter = new SqlParameter();
                parameter.ParameterName = "@postcode";
                parameter.Value = post;

                cmd.Parameters.Add(parameter);
                con.Open();
                SqlDataReader rdr = cmd.ExecuteReader();
                while (rdr.Read())
                {
                    listing.Add(new Postcode()
                    {
                        PostcodeID = Convert.ToInt32(rdr["PostcodeID"].ToString()),
                        postcode = rdr["postcode"].ToString(),
                        Locality = rdr["Locality"].ToString(),
                        State = rdr["State"].ToString(),
                        Country = rdr["Country"].ToString()
                    });
                }

                rdr.Close();
            }

            return Json(listing, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Help()
        {
            var model = DefaultConnection.Homes.Find(1);
            return View(model);
        }


        public ActionResult EmailForm()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EmailForm(EmailForm model)
        {
            if (ModelState.IsValid)
            {
                var body = "<p>Email From: {0} at "+model.FromEmail+"</p><p>Message:</p><p>{2}</p>";
                var message = new MailMessage();
                message.To.Add(new MailAddress("sailiemailservices@gmail.com"));  // replace with valid value 
                message.From = new MailAddress(model.FromEmail);  // replace with valid value
                message.Subject = model.Title;
                message.Body = string.Format(body, model.FromName, model.FromEmail, model.Message);
                message.IsBodyHtml = true;

                using (var smtp = new SmtpClient())
                {
                    var credential = new NetworkCredential
                    {
                        UserName = "azure_1deac5e7ef5ee3193eccd188f32361f5@azure.com",  // replace with valid value
                        Password = "caesar55Bc$"  // replace with valid value
                    };
                    smtp.Credentials = credential;
                    smtp.Host = "smtp.sendgrid.net";
                    smtp.Port = 587;
                    smtp.EnableSsl = true;
                    await smtp.SendMailAsync(message);
                    return RedirectToAction("Sent");
                }
            }
            return View(model);
        }


        public ActionResult Sent()
        {
            return View();
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Home model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                DefaultConnection.Homes.Add(new Home()
                {
                    About = model.About,
                    HelpName = model.HelpName,
                    HelpPhoneNumber = model.HelpPhoneNumber,
                    HelpEmail = model.HelpEmail
                });
                DefaultConnection.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        public ActionResult Details(int id)
        {
            var homeDetails = DefaultConnection.Homes.Where(h => h.HomeID == id).FirstOrDefault();

            if (homeDetails == null)
            {
                return HttpNotFound();
            }

            return View(homeDetails);
        }


        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var home = DefaultConnection.Homes.Where(c => c.HomeID == id).FirstOrDefault();
            return View(home);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Home model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                TryUpdateModel(model);
                DefaultConnection.Entry(model).State = EntityState.Modified;
                DefaultConnection.SaveChanges();
                return RedirectToAction("AdminIndex", model.HomeID);
            }
            catch
            {
                return View(model);
            }
        }

        public ActionResult CloseWindow()
        {
            ViewData["ShouldClose"] = true;

            return View();
        }

    }
}

Controllers/SSLController.cs
using SAILI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAILI.Controllers
{
    public class SSLController : Controller
    {
        // GET: SSL
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ConvertHTTPSLogin()
        {
            SecuredSocketLayer SSL = new SecuredSocketLayer();
            string returnUrl = null;

            returnUrl = SSL.SecuredLayerLogin();
            Response.Redirect(returnUrl);

            return View();
        }

        public ActionResult ConvertHTTPSRegister()
        {
            SecuredSocketLayer SSL = new SecuredSocketLayer();
            string returnUrl = null;

            returnUrl = SSL.SecuredLayerRegister();

            Response.Redirect(returnUrl);

            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/AdminIndex.cshtml
@model IEnumerable<SAILI.Models.Home>

@{
    ViewBag.Title = "AdminIndex";
    Layout = "~/Views/Shared/Membership.cshtml";
}

<h2>AdminIndex</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.About)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HelpName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HelpPhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HelpEmail)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.About)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HelpName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HelpPhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HelpEmail)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.HomeID }) |
            @Html.ActionLink("Details", "Details", new { id=item.HomeID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.HomeID })
        </td>
    </tr>
}

</table>

Views/Home/CloseWindow.cshtml
<% if ((bool)ViewData["ShouldClose"]) { %>
<script type="text/javascript">
    window.open('', '_self').close();
</script>
<% } %>

Views/Home/Contact.cshtml
@model SAILI.Models.Home

@{
    ViewBag.Title = "Help";
    Layout = "~/Views/Shared/Membership.cshtml";
}

<h2>Help</h2>

<div>
    <h4>Help</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.HelpName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HelpName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HelpPhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HelpPhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HelpEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HelpEmail)
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.HomeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Home/Create.cshtml
@model SAILI.Models.Home

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Home</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.About, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.About, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.About, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.HelpName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HelpName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HelpName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.HelpPhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HelpPhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HelpPhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.HelpEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HelpEmail, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HelpEmail, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/Home/Display.cshtml
@model IEnumerable<SAILI.Models.Postcode>

@if (Model != null)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.postcode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Locality)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.postcode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Locality)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Country)
                </td>
            </tr>
        }

    </table>

}

Views/Home/Edit.cshtml
@model SAILI.Models.Home

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Empty.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Home</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.HomeID)

        <div class="form-group">
            @Html.LabelFor(model => model.About, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.About, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.About, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HelpName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HelpName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HelpName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HelpPhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.HelpPhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HelpPhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HelpEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(Model => Model.HelpEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HelpEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Home/EmailForm.cshtml
@model SAILI.Models.EmailForm
@{
    ViewBag.Title = "Contact Email";
    Layout = "~/Views/Shared/Empty.cshtml";
}
<h2>@ViewBag.Title.</h2>

<section id="Form">

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <h4>Send your comments.</h4>
    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.FromName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FromName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.FromName)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.FromEmail, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FromEmail, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.FromEmail)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Title)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Message, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Message, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Message)
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Send" />
        </div>
    </div>
}
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


Views/Home/GetLocality.cshtml
@model IEnumerable<SAILI.Models.Postcode>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.postcode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Locality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.postcode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Locality)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
    </tr>
}

</table>

Views/Home/Help.cshtml
@model SAILI.Models.Home

@{
    ViewBag.Title = "Help";
    Layout = "~/Views/Shared/Membership.cshtml";
}

<h2>Help</h2>

<section id="Form">
    <h2>
       Contact Name: @Html.DisplayFor(model => model.HelpName)
    </h2>
    <h2>
       Phone Number: @Html.DisplayFor(model => model.HelpPhoneNumber)
    </h2>
    <h2>
       Email: @Html.DisplayFor(model => model.HelpEmail)
    </h2>
    <p>
        @Html.ActionLink("Email Help", "EmailForm", new { id = Model.HomeID })
    </p>
    <p>
        @Html.ActionLink("Return Home?", "Index", new { id = Model.HomeID })
    </p>

</section>

Views/Home/Index.cshtml

@model SAILI.Models.Home

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SAILI</h2>
 <hr />

<section id="Form">
    <h2>
        @Html.DisplayFor(model => model.About)
    </h2>
    <p>
        @Html.ActionLink("Login/Register", "ConvertHTTPSLogin", "SSL", routeValues: null, htmlAttributes: new { id = "loginLink", target = "_blank" })
    </p>
    <p>
        @Html.ActionLink("Leave Comment", "EmailForm", "Home")
    </p>
</section>
<p class="clear" />
<p class="clear" />

Views/Home/Sent.cshtml

@{
    ViewBag.Title = "Sent";
    Layout = "~/Views/Shared/Empty.cshtml";
}

<h2>Your message has been sent</h2>

<h2>
    @Html.ActionLink("Return Home", "Index", "Home")
</h2>