Models/Portfolio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using SAILI.Models;
using System.ComponentModel.DataAnnotations.Schema;

namespace SAILI.Models
{
    public class Portfolio
    {
        [Key]
        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        [Display(Name = "Portfolio ID")]
        public int PortfolioID { get; set; }

        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        public List<Buy> Buys { get; set; }

        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        public List<Sell> Sells { get; set; }

        [StringLength(128)]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public string TradingAccountID { get; set; }

        [ForeignKey("TradingAccountID"),System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public TraderAccount account { get; set; }

    }

    public class PortfolioViewModel
    {
        [Key]
        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        [Display(Name = "Portfolio ID")]
        public int PortfolioID { get; set; }

        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        public List<BuyViewModel> Buys { get; set; }

        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        public List<SellViewModel> Sells { get; set; }

        [StringLength(128)]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public string TradingAccountID { get; set; }

        [ForeignKey("TradingAccountID"), System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public TraderAccount account { get; set; }

    }

    public class Buy
    {
        [Key]
        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        [Display(Name = "Buy ID")]
        public int BuyID { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Trade Date")]
        public DateTime TradeDate { get; set; }

        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public int PortfolioId { get; set; }

        [ForeignKey("PortfolioId")]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public Portfolio portfolio { get; set; }

        [Display(Name = "Ticker Symbol")]
        public string TickerSymbol { get; set; }


        [Display(Name = "Purchase Price")]
        public decimal PurchasePrice { get; set; }

        [Display(Name = "Quantity")]
        public int Quantity { get; set; }

        [Display(Name = "Transaction Amount")]
        public decimal TransactionAmount { get; set; }

        [Display(Name = "Transaction Cost")]
        public decimal TransactionCost  { get; set; }

    }

    public class BuyViewModel
    {
        [Key]
        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        [Display(Name = "Buy ID")]
        public int BuyID { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Trade Date")]
        public DateTime TradeDate { get; set; }

        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public int PortfolioId { get; set; }

        [ForeignKey("PortfolioId")]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public Portfolio portfolio { get; set; }

        [Display(Name = "Ticker Symbol")]
        public string TickerSymbol { get; set; }

        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }


        [Display(Name = "Purchase Price")]
        public decimal PurchasePrice { get; set; }

        [Display(Name = "Quantity")]
        public int Quantity { get; set; }

        [Display(Name = "Transaction Amount")]
        public decimal TransactionAmount { get; set; }

        [Display(Name = "Transaction Cost")]
        public decimal TransactionCost { get; set; }

        [Display(Name = "Performance")]
        public decimal Performance { get; set; }

        [Display(Name = "Open")]
        public decimal Open { get; set; }

        [Display(Name = "Close")]
        public decimal Close { get; set; }

    }

    public class BuyModel
    {
        [Display(Name = "Symbol")]
        public string Symbol { get; set; }

        [Display(Name = "Open")]
        public decimal Open { get; set; }

        [Display(Name = "Purchase Price")]
        public decimal PurchasePrice { get; set; }

        [Display(Name = "Change")]
        public decimal Change { get; set; }

        [Display(Name = "Quantity")]
        public int Quantity { get; set; }

        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }

    }

    public class Sell
    {
        [Key]
        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        [Display(Name = "Sell ID")]
        public int SellID { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Transaction Date")]
        public DateTime TradeDate { get; set; }

        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        public int BuyID { get; set; }

        [ForeignKey("BuyID")]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public Buy buy { get; set; }

        [Display(Name = "Ticker Symbol")]
        public string TickerSymbol { get; set; }

        [Display(Name = "Quantity")]
        public int Quantity { get; set; }

        [Display(Name = "Purchase Price")]
        public decimal PurchasePrice { get; set; }

        [Display(Name = "Sold Price")]
        public decimal SoldPrice { get; set; }

        [Display(Name = "Transaction Amount")]
        public decimal TransactionAmount { get; set; }

        [Display(Name = "Transaction Cost")]
        public decimal TransactionCost { get; set; }

        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public int PortfolioID { get; set; }

    }

    public class SellViewModel
    {
        [Key]
        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        [Display(Name = "Sell ID")]
        public int SellID { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Transaction Date")]
        public DateTime TradeDate { get; set; }

        [System.Web.Mvc.HiddenInput(DisplayValue = true)]
        public int BuyID { get; set; }

        [ForeignKey("BuyID")]
        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public Buy buy { get; set; }

        [Display(Name = "Ticker Symbol")]
        public string TickerSymbol { get; set; }

        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }

        [Display(Name = "Quantity")]
        public int Quantity { get; set; }

        [Display(Name = "Purchase Price")]
        public decimal PurchasePrice { get; set; }

        [Display(Name = "Sold Price")]
        public decimal SoldPrice { get; set; }

        [Display(Name = "Transaction Amount")]
        public decimal TransactionAmount { get; set; }

        [Display(Name = "Transaction Cost")]
        public decimal TransactionCost { get; set; }

        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public int PortfolioID { get; set; }
    }




    public class Historical
    {
        [Display(Name = "Symbol")]
        public string Symbol { get; set; }

        public List<HistoricalPrices> historicalPrices { get; set; }
    }

    public class HistoricalPrices
    {
        [Display(Name = "Date")]
        public string Date { get; set; }

        [Display(Name = "Open")]
        public decimal Open { get; set; }

        [Display(Name = "Close")]
        public decimal Close { get; set; }

    }

    public class TransactionCost
    {
        public const Double BuyCost = .01;
        public const Double SellCost = .25; 
    }
}

Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAILI.Models;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;
using Microsoft.AspNet.Identity;
using DotNet.Highcharts.Options;
using DotNet.Highcharts.Helpers;
using DotNet.Highcharts.Enums;
using System.Net;
using System.Data.Entity;

namespace SAILI.Controllers
{
    [Authorize(Roles = "Trader")]
    public class PortfolioController : Controller
    {
        private Vector<Listings> listing = new Vector<Listings>();
        private ApplicationDbContext DefaultConnection = new ApplicationDbContext();
        private SailiRepository repository = new SailiRepository();
        private string databaseConnection = ConfigurationManager.ConnectionStrings["SailiDbContext"].ConnectionString;

        // GET: Portfolio
        public ActionResult Index()
        {
            string symbol = repository.GetAllSymbols();
            List<Listings> price = null;
            DataSerializer<string>.GetPriceListings(ref price, symbol);
            return View(price);
        }

        public ActionResult StockEnquiry(Listings list)
        {
            return View(list);
        }

        //Method serves two
        public ActionResult ConfirmBuy(string symbol)
        {
            BuyModel model = null;
            List<Listings> listings = null;
            string[] temp = symbol.Split(',');

            if(temp.Count() < 2) // means it has come from navbar request
            {
                DataSerializer<string>.GetSingleListings(ref listings, symbol);

                foreach(var company in listings)
                {
                    model = new BuyModel();
                    model.Symbol = company.Symbol;
                    model.Open = company.Open;
                    model.PurchasePrice = company.Close;
                    model.CompanyName = company.CompanyName;
                    model.Change = company.Close - company.Open;
                }
            }
            else // Has come from a Portfolio request
            {
                model = new BuyModel();
                model.Symbol = temp[0];
                model.Open = Convert.ToDecimal(temp[1]);
                model.PurchasePrice = Convert.ToDecimal(temp[2]);
                model.Change = Convert.ToDecimal(temp[3]);
                model.CompanyName = temp[4];
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Buy(BuyModel model)
        {
            if (model.Quantity < 1)
            {
                TempData["BuyException"] = "Buying 0 stocks... Please try again";
                return RedirectToAction("ConfirmBuy", new { symbol = model.Symbol });
            }

            decimal transactionCost = (decimal)TransactionCost.BuyCost * (model.Quantity * model.PurchasePrice);
            string[] temp = model.Symbol.Split(',');
            SailiRepository repository = new SailiRepository();
            Buy buy = new Buy();
            buy.TradeDate = DateTime.Now;
            buy.TickerSymbol = temp[0];
            buy.Quantity = model.Quantity;
            buy.PurchasePrice = model.PurchasePrice;
            buy.TransactionAmount = model.Quantity * model.PurchasePrice + transactionCost;
            buy.TransactionCost = transactionCost;
            buy = repository.Finalizebuy(buy, User.Identity.GetUserId());

            Owner owner = repository.GetOwner(User.Identity.GetUserId());

            TraderAccount trader = repository.GetTrader(owner.OwnerID);

            return RedirectToAction("Details", "TraderAccount", new
            {
                TradingAccountID = trader.TradingAccountID
            });
        }

        public ActionResult ConfirmSell(string tradingAccountID, int buyID)
        {
            if(tradingAccountID == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Portfolio portfolio = null;
            SailiRepository repository = new SailiRepository();
            portfolio = repository.GetPortfolio(tradingAccountID);

            if (portfolio == null)
                return HttpNotFound();

            var buy = DefaultConnection.Buys.Find(buyID);

            if (!buy.PortfolioId.Equals(portfolio.PortfolioID))
            {
                DataSerializer<string>.SecurityPriorityNumberOne(User.Identity.GetUserId());
                return new HttpStatusCodeResult(HttpStatusCode.Unauthorized);
            }

            Company company = new Company();
            List<Listings> listings = new List<Listings>();
            company = repository.GetCompany(company, buy.TickerSymbol);
            DataSerializer<string>.GetSingleListings(ref listings, company.Symbol);
            Sell sell = new Sell();
            sell.BuyID = buy.BuyID;
            sell.TickerSymbol = buy.TickerSymbol;
            sell.PurchasePrice = buy.PurchasePrice;

            foreach(var list in listings)
            {
                if (list.Symbol.Equals(sell.TickerSymbol))
                    sell.SoldPrice = list.Close;
            }

            TempData["ShareQuantity"] = buy.Quantity;
            TempData["CompanyName"] = company.CompanyName;

            return View(sell);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Sell(Sell model)
        {
            try
            {
                Buy buy = DefaultConnection.Buys.Find(model.BuyID);
                Portfolio portfolio = DefaultConnection.Portfolios.Find(buy.PortfolioId);
                SailiRepository repository = new SailiRepository();
                Owner owner = new Owner();
                owner = repository.GetOwner(User.Identity.GetUserId());
                TraderAccount trader = new TraderAccount();
                trader = repository.GetTrader(owner.OwnerID);

                if (model.Quantity > buy.Quantity)
                {
                    TempData["SellException"] = "Selling more stocks than what is baught... Please try again";
                    return RedirectToAction("ConfirmSell", new { tradingAccountID = portfolio.TradingAccountID, buyID = buy.BuyID });
                }
                decimal transactionCost = (decimal)TransactionCost.SellCost * (model.Quantity * model.SoldPrice);
                model.PortfolioID = portfolio.PortfolioID;
                model.TradeDate = DateTime.Now;
                model.BuyID = buy.BuyID;
                model.TransactionCost = transactionCost;
                model.TransactionAmount = model.Quantity * model.SoldPrice - transactionCost;
                trader.Balance = trader.Balance + model.TransactionAmount;
                buy.Quantity = buy.Quantity - model.Quantity;
                TryUpdateModel(buy);
                DefaultConnection.Entry(buy).State = EntityState.Modified;
                DefaultConnection.SaveChanges();
                TryUpdateModel(trader);
                DefaultConnection.Entry(trader).State = EntityState.Modified;
                DefaultConnection.SaveChanges();
                TryUpdateModel(model);
                DefaultConnection.Sells.Add(model);
                DefaultConnection.SaveChanges();

                return RedirectToAction("Details", "TraderAccount", new
                {
                    TradingAccountID = portfolio.TradingAccountID
                });
            }
            catch
            {
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult GetListing(string symbol)
        {
            List<Listings> listings = null;
            List<Company> companies = null;
            Company company = null;
            company = repository.GetCompany(company, symbol);
            if(company != null)
            {
                companies = new List<Company>();
                companies.Add(company);
                DataSerializer<string>.GetCurrentPrice(ref listings, companies);
                return Json(listings, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false });
            }          
        }
    }
}

Views/Portfolio/ConfirmBuy.cshtml
@model SAILI.Models.BuyViewModel
@{
    ViewBag.Title = "Confirm Buy";
    Layout = "~/Views/Shared/Membership.cshtml";
}

<h2>Confirm Buy</h2>

@using (Html.BeginForm("Buy", "Portfolio", FormMethod.Post, new { id = "buyForm", @class = "navbar-right" }))
{
    @Html.AntiForgeryToken()
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Symbol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Open)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PurchasePrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Change)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th></th>
        </tr>
        <tr>
            <td style="color: #0b0c0b">
                @Html.DisplayFor(model => model.Symbol)
                @Html.ValidationMessageFor(model => model.Symbol, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Symbol)
            </td>
            <td style="color: #0b0c0b">
                @Html.DisplayFor(model => model.CompanyName)
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.CompanyName)
            </td>
            <td style="color: #0b0c0b">
                @Model.Open.ToString("C")
                @Html.ValidationMessageFor(model => model.Open, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Open)
            </td>
            <td style="color: #0b0c0b">
                @Model.PurchasePrice.ToString()
                @Html.ValidationMessageFor(model => model.PurchasePrice, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.PurchasePrice)
            </td>
            @if (Model.Change < 0)
            {
                <td style="color: #fc3d37">
                    @Model.Change.ToString("C")
                    @Html.ValidationMessageFor(model => model.Change, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Change)
                </td>
                <td>
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </td>
                <td>
                    <input type="submit" value="Buy" />
                </td>
            }
            else if (Model.Change > 0)
            {
                <td style="color: #108810">
                    @Model.Change.ToString("C")
                    @Html.ValidationMessageFor(model => model.Change, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Change)
                </td>
                <td>
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </td>
                <td>
                    <input type="submit" value="Buy" />
                </td>
            }
            else
            {
                <td style="color: #0b0c0b">
                    @Model.Change.ToString("C")
                    @Html.ValidationMessageFor(model => model.Change, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Change)
                </td>
                <td>
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </td>
                <td>
                    <input type="submit" value="Buy" />
                </td>
            }
        </tr>
    </table>
    if (TempData["BuyException"] != null)
    {
        <p style="color: #fc3d37"><strong>@TempData["BuyException"]</strong></p>
    }
}



Views/Portfolio/ConfirmSell.cshtml
@model SAILI.Models.Sell

@{
    ViewBag.Title = "ConfirmSell";
    Layout = "~/Views/Shared/Membership.cshtml";
    decimal Change = Model.SoldPrice - Model.PurchasePrice;
}

<h2>ConfirmSell</h2>

@using (Html.BeginForm("Sell", "Portfolio", FormMethod.Post, new { id = "sellForm", @class = "navbar-right" }))
{
    @Html.AntiForgeryToken()

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BuyID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TickerSymbol)
            </th>
            <th>
                @Html.Label("Company Name")
            </th>
            <th>
                @Html.Label("Share Quantity")
            </th>
            <th>
                @Html.Label("Paid Price")
            </th>
            <th>
                @Html.Label("Current Price")
            </th>
            <th>
                @Html.Label("Change")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th></th>
        </tr>
        <tr>
            <td style="color: #0b0c0b">
                @Html.DisplayFor(model => model.BuyID)
                @Html.ValidationMessageFor(model => model.BuyID, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.BuyID)
            </td>
            <td style="color: #0b0c0b">
                @Html.DisplayFor(model => model.TickerSymbol)
                @Html.ValidationMessageFor(model => model.TickerSymbol, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.TickerSymbol)
            </td>
            <td style="color: #0b0c0b">
                @TempData["CompanyName"]
            </td>
            <td style="color: #0b0c0b">
                @TempData["ShareQuantity"]
            </td>
            <td style="color: #0b0c0b">
                @Model.PurchasePrice.ToString("C")
                @Html.ValidationMessageFor(model => model.PurchasePrice, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.PurchasePrice)
            </td>
            <td style="color: #0b0c0b">
                @Model.SoldPrice.ToString("C")
                @Html.ValidationMessageFor(model => model.SoldPrice, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.SoldPrice)
            </td>
            @if (Change < 0)
            {
                <td style="color: #fc3d37">
                    @Change.ToString("C")
                </td>
                <td>
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Quantity)
                </td>
                <td>
                    <input type="submit" value="Sell" />
                </td>
            }
            else if (Change > 0)
            {
                <td style="color: #108810">
                    @Change.ToString("C")
                </td>
                <td>
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Quantity)
                </td>
                <td>
                    <input type="submit" value="Sell" />
                </td>
            }
            else
            {
                <td style="color: #0b0c0b">
                    @Change.ToString("C")
                </td>
                <td>
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Quantity)
                </td>
                <td>
                    <input type="submit" value="Sell" />
                </td>
            }
        </tr>
</table>
}
@if (TempData["SellException"] != null)
{
    <p style="color: #fc3d37"><strong>@TempData["SellException"]</strong></p>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>




Views/Portfolio/Get200.cshtml
@model IEnumerable<SAILI.Models.Listings>

@{
    ViewBag.Title = "Get 200";
    Layout = "~/Views/Shared/Membership.cshtml";
}

<h1><b>Get 200</b></h1>

<p>
    @Html.ActionLink("Return Home?", "CloseWindow")
</p>
<table class="table">
    <tr>
        <th style="color: #0b0c0b">
            @Html.DisplayNameFor(model => model.Symbol)
        </th>
        <th style="color: #0b0c0b">
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th style="color: #0b0c0b">
            @Html.DisplayNameFor(model => model.Open)
        </th>
        <th style="color: #0b0c0b">
            @Html.DisplayNameFor(model => model.Close)
        </th>
        <th style="color: #0b0c0b">
            @Html.DisplayNameFor(model => model.Change)
        </th>>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @if (item == null)
            {
                break;
            }
            <td style="color: #0b0c0b">
                @Html.DisplayFor(modelItem => item.Symbol)
            </td>
            <td style="color: #0b0c0b">
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td style="color: #0b0c0b">
                @item.Open.ToString("C")
            </td>
            <td style="color: #0b0c0b">
                @item.Close.ToString("C")
            </td>
            @if (item.Change < 0)
            {
                <td style="color: #fc3d37">
                    @item.Change.ToString("C")
                </td>
            }
            else if (item.Change > 0)
            {
                <td style="color: #108810">
                    @item.Change.ToString("C")
                </td>
            }
            else
            {
                <td style="color: #0b0c0b">
                    @item.Change.ToString("C")
                </td>
            }
            <td style="color: #0b0c0b">
                @Html.ActionLink("Buy", "Edit")
            </td>
        </tr>
    }
</table>
